### ISSUE TITLE
Web版が起動しない

### ISSUE THREAD

**Issue by yandod** [Hiekichi/Poker#1]
Web版を起動したところ下記のエラーに遭遇しました

<pre>
Traceback (most recent call last):
  File "/lib/python312.zip/_pyodide/_base.py", line 522, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python312.zip/_pyodide/_base.py", line 356, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 3, in 
  File "/lib/python3.12/site-packages/pyxel/cli.py", line 178, in run_python_script
    runpy.run_path(python_script_file, run_name="__main__")
  File "", line 286, in run_path
  File "", line 98, in _run_module_code
  File "", line 88, in _run_code
  File "Poker240.py", line 334, in 
    App()
  File "Poker240.py", line 37, in __init__
    pyxel.init(240,240,"Poker",fps=24)
TypeError: init() takes 2 positional arguments but 3 were given
</pre>

**Comment by Hiekichi** [comment]
ありがとうございました。
エラーメッセージをいただいたことで速やかに解決できました。
＃Web版以外はなぜ動いていたんだろう・・・？
